@extends('layouts.head')
@section('content')
<div class="container mt-5">
    <div class="text-center">
        <h3 style="color: #4479bd;" class="p-2">Privacy Policy</h3>
    </div>
    <div class="card rounded p-4">
        
        <p>
           We at Romil Sewa Sanstha respect your concerns about privacy and value the relationship we have with you. We are committed to the ethical collection, retention and use of information that you provide to us about yourself (“Personal Information”) on this site https://romilsewasanstha.org/ (“Site”). This policy describes the types of personal information we collect, how we may use that information and with whom we may share it when you visit our site or use our services (collectively the “Services”). Our Privacy Policy also describes the measures we take to protect the security of the information. In addition, we describe the choices you can make about how we use the information you provide to us. We also tell you how you can reach us to update your contact information, remove your name from our mailing lists, or answer any questions you may have about our privacy practices.
We maintain full confidentiality of all donors and contributors on our mailing and email lists, which will neither be sold to nor exchanged with any other organization or commercial enterprise, and we honour donors’ opt-out choices in our mail, email, phone and other solicitations.
Information We Collect and How We Use It
We may collect information about you directly from you and from third parties, as well as automatically through your use of our Site or Services to extend services like for our internal purposes, processing of your donations, providing receipts and tax exemption certificates, sending regular updates about the work we do for children, respond to your queries and apprising you of the new opportunities to help deprived and marginalized children of India in a better way. We seek your personal information when you make a donation, request a communication from us, register for an on-ground event, pledge support to our work and campaigns and apply for working or volunteer with Romil Sewa Sanstha. This information may be sought over the phone, through the website, via email or by the means of face-to-face interaction. You may choose to provide personal information either by phone, mail or on our Site. Certain areas and features of our Site and Services may require registration. To register, you must provide your name, address, email address, log in and password. We may also request from you or allow you to submit additional optional information, depending on the type of communication or transaction the personal information we collect may include, but is not limited to, your name, postal address, date of birth, PIN code, telephone numbers, mobile phone numbers, your organization’s name, email addresses, credit/debit card information, bank information or billing information. Irrespective of the mode in which we receive your personal information, we make all earnest attempts to honour your privacy.
Email Communications
When you ask us to send you an email such as a free email newsletter, you may provide us with certain information such as your email address so we can fulfil your request. You may choose to provide additional information as well, such as your postal address and phone number.
Donations
When you make a donation through our Site, we may ask you to submit certain personal information (such as credit card information) so we can process your donation. We also maintain your contact information in our records so we can contact you to provide Romil Sewa Sanstha’s program information and information on additional giving opportunities.
Refunds and Cancellations
We take the utmost care to process donations as per the instructions given by our donors, online and offline. However, in case of an unlikely event of an erroneous donation, we will respond to the donor within 7 working days of receiving a valid request for a refund from the donor.
The timely refund of the donation will depend upon the type of credit card/banking instrument used during the transaction. The donor will have to send us a written request for a refund within 2 days of making the donation along with-
Proof of the deduction of the donation amount.
In cases where the donation receipt has already been issued to the donor, the donor will have to return the original receipt to us at our office address.
If the tax exemption certificate is already issued, then we are sorry but we will not be able to refund the donation. However, in case of a valid refund request due to an error on our part, we will refund the donation and bear the costs of the same.
If the donor doesn’t write within two days, then a refund is not possible.
Questionnaires and Surveys
We occasionally may ask visitors to our Site to complete online surveys and opinion polls about their activities, attitudes and interests. These surveys help us understand the needs of our visitors. We do not keep any personal information about you in connection with your participation in a Site survey unless you specifically agree to provide this information.
Cookies and Web Beacons
We use cookies and other tracking mechanisms to track information about your use of our Site or Services. We may combine this information with other personal information we collect from you. Cookies are pieces of electronic information which will be sent by Romil Sewa Sanstha for record-keeping purposes when you log onto our website. These will be placed in your computer’s hard disk and enable us to recognise you as a user when you next visit. Some cookies allow us to make it easier for you to navigate our Site and Services, while others are used to enable a faster log-in process or to allow us to track your activities at our Site and Service. There are two types of cookies: session and persistent cookies.
Session Cookies – Session cookies exist only during an online session. They disappear from your computer when you close your browser or turn off your computer. We use session cookies to allow our systems to uniquely identify you during a session or while you are logged in to the Site. This allows us to process your online transactions and requests and verify your identity after you have logged in and as you move through our Site.
Persistent cookies – Persistent cookies remain on your computer after you have closed your browser or turned off your computer. We use persistent cookies to track aggregate and statistical information about user activity.
 
Third-Party Cookies –
We may also engage third parties to track and analyse non-personally and personally identifiable Site data. We use the data collected by such third parties to help us administer and improve the quality of the Site and to analyse Site usage. Such third parties may combine the information that we provide about you with other information that they have collected. This Privacy Policy does not cover such third parties’ use of the data.
Disabling Cookies –
Most web browsers automatically accept cookies, but if you prefer, you can edit your browser options to block them in the future. The Help portion of the toolbar on most browsers will tell you how to prevent your computer from accepting new cookies, how to have the browser notify you when you receive a new cookie or how to disable cookies altogether. Visitors to our Site who disable cookies will be able to browse certain areas of the Site, but some features may not function.
Clear GIFs, pixel tags and other technologies –
Clear GIFs are tiny graphics with a unique identifier, similar in function to cookies. In contrast to cookies, which are stored on your computer’s hard drive, clear GIFs are embedded invisibly on web pages. We may use clear GIFs (a.k.a. web beacons, web bugs or pixel tags), in connection with our Site to, among other things, track the activities of Site visitors, help us manage content and compile statistics about Site usage. We and our third-party service providers also use clear GIFs in HTML emails to our customers, to help us track email response rates, identify when our emails are viewed and track whether our emails are forwarded.
Third-Party Analytics –
We use automated devices and applications, such as Google Analytics, to evaluate usage of our Site and, to the extent permitted, our Application. We also may use other analytic means to evaluate our Services. We use these tools to help us improve our Services, performance and user experiences. We do not share your personal information with these third parties.
Information We Share
Romil Sewa Sanstha does not sell, rent, trade or otherwise disclose personal information about our Site visitors (nor our offline donors), except as described here. We share information provided by our Site visitors with service providers that we have retained to perform services on our behalf ― for example, to process donations, send direct mail, emailers, greeting cards, make phone calls, and others. We may share your information like phone numbers, email addresses, etc. with these agencies so that they can perform these activities efficiently. These service providers are not authorized by us to use or disclose the information except as necessary to perform services on our behalf or to comply with legal requirements. However, since we do not have complete control over these third parties, we cannot guarantee your privacy. In addition, we may disclose information about you (i) if we are required to do so by law, (ii) in response to a request from law enforcement authorities or other government officials, (iii) when we believe disclosure is necessary or appropriate to prevent physical harm or financial loss or in connection with an investigation of suspected or actual illegal activity, or (iv) to our affiliates or subsidiaries.
We reserve the right to transfer any information we have about you in the event we sell or transfer all or a portion of our business or assets. Should such a sale or transfer occur, we will use reasonable efforts to try to direct the transferee to use the personal information you have provided through this Site in a manner that is consistent with this Privacy Policy.
Links to Other Sites
The Site contains links to other websites for the benefit of its visitors. These sites operate independently from our site and are not under our control. We are not responsible for the content of these sites, any products or services that may be offered through these sites or any other use of these sites. Romil Sewa Sanstha is not expressly or impliedly responsible for, or liable to any loss or damage caused to you by the collection, use and retention of Personal Information by such websites in any manner whatsoever. This Privacy Policy does not apply to such other websites. These sites may have their own privacy policies in place, which we strongly suggest you review if you visit any linked sites.
Security
Romil Sewa Sanstha has the necessary security mechanisms in place and only designated employees to have access to your personal information. We maintain administrative, technical and physical safeguards to protect against unauthorized disclosure, use, alteration or destruction of the personal information in our possession. All online transactions are done on a secure server. When you provide the credit card information to make a donation, we use the industry standard for Internet security ― Secure Socket Layer (SSL) technology ― to help protect the information you provide. This Internet encryption standard scrambles data as it travels from your computer to our server. Please note, however, that perfect security does not exist on the Internet. You’ll know that you’re in a secure area of our Site when a “lock” icon appears on your screen and the “http” portion of our URL address changes to “https.” The “s” stands for “secure.”
Copyright Protection
All content on this Site including graphics, text, icons, interfaces, audio clips, logos, images and software is the property of Romil Sewa Sanstha and/or its content suppliers and is protected by Indian and international copyright laws. The arrangement and compilation (meaning the collection, arrangement, and assembly) of all content on this Site is the exclusive property of Romil Sewa Sanstha and protected by Indian and international copyright laws. Permission is given to use the resources of this Site only for the purposes of making enquiries, making a donation or funding any of Romil Sewa Sanstha’s initiatives. Any other use, including the reproduction, modification, distribution, transmission, republication, display or performance, of the content on this Site can only be made with the permission of Romil Sewa Sanstha. All other trademarks, brands and copyrights other than those belonging to Romil Sewa Sanstha belong to their respective owners and are their property.
Updates to This Privacy Policy
We may change or update portions of this Privacy Policy at any time and without prior notice to you. Please check back from time to time so you are aware of any changes or updates to the Policy. You may reach out to us if you have any queries about any changes made to our practices.
How to Contact Us
If you would like us to update your contact information or remove your name from our email or postal mailing lists, or if you have any questions about our information practices, please contact us by visiting https://romilsewasanstha.org/ or Emailing us at urvashi.sethisodhi@gmail.com.
You can write to us at:
Romil Sewa Sanstha
C356 Defence Colony, New Delhi 110024
Or, Email us at: urvashi.sethisodhi@gmail.com

        </p>
    </div>
</div>
@endsection