@extends('layouts.head')
@section('content')
<div class="container mt-5">
    <div class="text-center">
        <h3 style="color: #4479bd;" class="p-2">Terms & Conditions</h3>
    </div>
    <div class="card rounded p-4">
        
        <p>
            This website is owned and operated by Romil Sewa Sanstha (“Romil Sewa Sanstha”, “we,” “us” or “our”). Romil Sewa Sanstha provides this website, including all information, software and services available from this website, to you, the user, conditioned upon your acceptance of all the terms, conditions, policies and notices described herein. Your use of the website constitutes your agreement to all such terms, conditions, policies and notices.
Your Use of the Website
This website is for your personal and non-commercial use. As a condition to your use of the website, you warrant to Romil Sewa Sanstha that you will not use the website for any purpose that is unlawful or prohibited by these General Terms and Conditions.
Privacy Policy
You explicitly consent to the collection, hosting, use, disclosure and other processing or handling of information as described in the Romil Sewa Sanstha’s Privacy Policy located at https://romilsewasanstha.org/ as such policy may be amended by Romil Sewa Sanstha in its sole discretion from time to time.
Accuracy, Completeness and Timeliness of Information on the Website
We strive to provide accurate information on our website. We are not responsible, however, if information we make available on this website is not accurate, complete or current. The materials on this website are provided for general information only and should not be relied upon or used as the basis for making any decisions without consulting primary or more accurate, more complete or more timely sources of information. Any reliance on the materials on this website will be at your own risk. This website may contain certain historical information. Historical information is not current and is provided for your reference only. We reserve the right to modify the contents of this website at any time, but we have no obligation to update any information on the website. You agree that it is your responsibility to monitor changes to the website.
Use of Materials From the Website
Except where explicitly stated otherwise, this website and all of its content (including but not limited to software, files, graphics and data) are the property of and owned by Romil Sewa Sanstha and/or its affiliates, suppliers or licensors and are protected by copyright, trademark and other laws of India and other countries. You may display and electronically copy, download and print hard-copy versions of the materials contained on the website for your personal and non-commercial use, provided that you do not modify or delete any copyright, trademark or other proprietary notice that appears on the materials you copy, download or print. When you display, copy, download or print any materials on or from the website, they are provided to you by Romil Sewa Sanstha and/or its affiliates, suppliers or licensors under a license that is revocable at will by Romil Sewa Sanstha. Romil Sewa Sanstha and/or its affiliates, suppliers or licensors retain full and complete title to the materials and to any and all of the associated intellectual property rights. Any other use of the materials on the website, including but not limited to the modification, distribution, transmission, performance, broadcast, reproduction, publication, licensing, reverse engineering, transfer or sale of, or the creation of derivative works from, any materials, information, software, products or services obtained from the website, without the prior written permission of Romil Sewa Sanstha, is expressly prohibited. Contact us for getting permission to undertake any of these activities on
Romil Sewa Sanstha
Attn: Communications
Romil Sewa Sanstha
C356 Defence Colony, New Delhi 110024
https://romilsewasanstha.org/contact-us
Materials You Submit
The website may contain features and functionality permitting you to publish, upload, post, display or otherwise submit (collectively, “Publish”) certain information, comments and other content that may be viewed by us, the general public and other users of the website. You are responsible for any information, comments or other content published by you or any person using your computer. You agree not to publish any information, comments or other data that is or may reasonably be considered libellous, defamatory, obscene, threatening, invasive of privacy or publicity rights, infringing or misappropriating of intellectual property rights, abusive, illegal or otherwise objectionable, or which may constitute or encourage a criminal offence, violate the rights of any party or otherwise give rise to liability or violate any law, or consists of or contains software viruses, political campaigning, commercial solicitation, chain letters, mass mailings or any form of “spam.” You may not use a false email address, impersonate any person or entity or otherwise mislead as to the origin of information, comments or other content Published by you. We reserve the right (but not the obligation) to remove or edit such content but do not regularly review posted content provided.
You may not use the website in any manner that could damage, disable, overburden or impair any Romil Sewa Sanstha server (including the servers of any Romil Sewa Sanstha’s third-party provider) or the network(s) connected to any Romil Sewa Sanstha server (including the servers of any Romil Sewa Sanstha’s third-party provider), or interfere with any other party’s use and enjoyment of all or any portion of the website. You may not attempt to gain unauthorized access to any restricted web pages or any web pages requiring registration in order to view, through hacking, password mining or any other means. You may not obtain or attempt to obtain any materials or information through any means not intentionally made available through the website by Romil Sewa Sanstha.  Any access or use of web pages requiring registration are subject to your registration on the site and is further governed by the Restricted Sites Terms and Conditions available at https://romilsewasanstha.org/
If you do Publish information, comments or other content on or to the website, and unless we indicate otherwise, you grant us a nonexclusive, royalty-free, perpetual, irrevocable and fully sub licensable right to use, reproduce, modify, adapt, publish, translate, create derivative works from, distribute and display such content throughout the world in any media. You represent and warrant that you own or otherwise control all of the rights to the content that you post; that the content is accurate; that use of the content you supply does not violate these General Terms and Conditions, and where applicable, the Restricted Sites Terms and Conditions and will not cause injury to any person or entity; and that you will indemnify us, our affiliates and our respective directors, officers, employees, representatives and agents for all claims arising from content you Publish, that is Published from your computer or that is Published using your user name and password, if any. We take no responsibility and assume no liability for any content Published by you, from your computer or using your user name and password, if any.
Disclaimers
YOUR USE OF THIS WEBSITE IS AT YOUR OWN RISK. THE WEBSITE IS PROVIDED ON AN “AS IS” AND “AS AVAILABLE” BASIS. WE RESERVE THE RIGHT TO RESTRICT OR TERMINATE YOUR ACCESS TO THE WEBSITE OR ANY FEATURE OR ANY PART THEREOF AT ANY TIME. Romil Sewa Sanstha EXPRESSLY DISCLAIMS ALL WARRANTIES OF ANY KIND, WHETHER EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE AND ANY WARRANTIES THAT MATERIALS ON THE WEBSITE ARE NONINFRINGING; THAT ACCESS TO THE WEBSITE WILL BE UNINTERRUPTED OR ERROR-FREE; THAT THE WEBSITE OR ANY CONTENT SUBMITTED TO THE WEBSITE WILL BE SECURE; THAT THE WEBSITE OR THE SOFTWARE AND SERVERS THAT MAKE THE WEBSITE AVAILABLE WILL BE VIRUS-FREE; OR THAT INFORMATION ON THE WEBSITE WILL BE COMPLETE, ACCURATE OR TIMELY. IF YOU DOWNLOAD ANY MATERIALS FROM THIS WEBSITE, YOU DO SO AT YOUR OWN DISCRETION AND RISK. YOU WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO YOUR COMPUTER SYSTEM OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF ANY SUCH MATERIALS. NO ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM Romil Sewa Sanstha OR THROUGH OR FROM THE WEBSITE SHALL CREATE ANY WARRANTY OF ANY KIND. Romil Sewa Sanstha DOES NOT MAKE ANY WARRANTIES OR REPRESENTATIONS REGARDING ANY RESULTS OBTAINED BY YOU IN RELYING ON THE MATERIALS ON THIS WEBSITE OR THE USE OF THE MATERIALS ON THIS WEBSITE IN TERMS OF THEIR COMPLETENESS, CORRECTNESS, ACCURACY, ADEQUACY, USEFULNESS, TIMELINESS, RELIABILITY OR OTHERWISE. IN CERTAIN STATES, THE LAW MAY NOT PERMIT THE DISCLAIMER OF WARRANTIES, SO ALL OR PORTIONS OF THE ABOVE DISCLAIMER MAY NOT APPLY TO YOU.
Limitation of Liability
TO THE FULLEST EXTENT PERMITTED UNDER APPLICABLE LAW, YOU UNDERSTAND AND AGREE THAT NO MEMBER OF THE Romil Sewa Sanstha GROUP (AS DEFINED BELOW) SHALL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, CONSEQUENTIAL, PUNITIVE OR ANY OTHER DAMAGES RELATING TO OR RESULTING FROM (I) YOUR USE OR INABILITY TO USE THIS WEBSITE OR ANY OTHER WEBSITE YOU ACCESS THROUGH A LINK FROM THIS SITE, (II) FROM ANY ACTIONS WE TAKE OR FAIL TO TAKE AS A RESULT OF ELECTRONIC MAIL MESSAGES YOU SEND US; (III) THE PUBLISHING OF ANY INFORMATION, COMMENTS OR OTHER INFORMATION ON OR TO THE WEBSITE BY YOU OR ANY PERSON USING YOUR COMPUTER; OR (IV) THE USE BY ANY THIRD PARTY OF YOUR USER NAME OR PASSWORD. THESE INCLUDE DAMAGES FOR ERRORS, OMISSIONS, INTERRUPTIONS, DEFECTS, DELAYS, COMPUTER VIRUSES, YOUR LOSS OF PROFITS, LOSS OF DATA, UNAUTHORIZED ACCESS TO OR ALTERATION OF YOUR TRANSMISSIONS OR DATA, AND OTHER TANGIBLE AND INTANGIBLE LOSSES. THIS LIMITATION APPLIES REGARDLESS OF WHETHER THE DAMAGES ARE CLAIMED UNDER THE TERMS OF A CONTRACT, AS OF NEGLIGENCE, OR OTHERWISE ARISE OUT OF OR IN CONNECTION WITH THE USE, INABILITY TO USE OR PERFORMANCE OF THE INFORMATION, SERVICES, PRODUCTS OR MATERIALS AVAILABLE FROM THIS WEBSITE, AND EVEN IF WE OR OUR REPRESENTATIVES HAVE BEEN NEGLIGENT OR HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES. BECAUSE SOME JURISDICTIONS DO NOT ALLOW LIMITATIONS ON HOW LONG AN IMPLIED WARRANTY LASTS, OR THE EXCLUSION OR LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, THE ABOVE LIMITATION MAY NOT APPLY TO YOU.
Indemnification
You will indemnify and hold harmless Romil Sewa Sanstha, its affiliates and their respective current, future or former officers, directors, partners, employees, agents, contractors, licensors, suppliers and their successors or assigns (collectively, the “Romil Sewa Sanstha Group”) on demand, from and against any and all fines, penalties, liabilities, losses and other damages of any kind whatsoever (including attorneys’ and experts’ fees) incurred by any of the members of the Romil Sewa Sanstha Group, and, if directed by Romil Sewa Sanstha, shall defend the Romil Sewa Sanstha Group against (i) all claims that any information, data or other materials provided or Published by you in connection with the website or these General Terms and Conditions, or use thereof by any member of the Romil Sewa Sanstha Group, infringes, misappropriates or otherwise violates any patent, trademark, copyright, trade secret or other intellectual property, proprietary or privacy right of a third party, or that violates any law, rule or regulation; (ii) all claims arising from fraud, intentional misconduct, criminal acts or gross negligence by you; and (iii) all claims otherwise arising due to a failure by you to comply with any term or condition of these General Terms and Conditions.
Featured Links
This website may contain hyperlinks to other Internet websites. These hyperlinks are provided for your information and convenience only. Romil Sewa Sanstha does not control these other websites and is not responsible for their content; nor does Romil Sewa Sanstha’s inclusion of hyperlinks to such websites imply any endorsement or approval of the material on such websites or any association with their operators. Check the URL address provided in your browser to determine whether you are still in this Romil Sewa Sanstha website or have moved to another site.
Linking
Romil Sewa Sanstha permits linking to content on our website. Linking should not suggest that Romil Sewa Sanstha promotes or encourages any third party’s causes, ideas, websites, products or services. Linking should not use Romil Sewa Sanstha’s content for inappropriate commercial purposes or in any way that is unlawful or harmful to any other person or entity. Romil Sewa Sanstha reserves the right to withdraw permission for any link.
Copyright
Except for material in the public domain under Indian copyright law, all material contained on the website (including all software, HTML code, Java applets, Active X controls and other code) is protected by applicable Indian and foreign copyright laws. Except as otherwise expressly provided in these General Terms and Conditions, you may not copy, distribute, transmit, display, perform, reproduce, publish, license, modify, rewrite, create derivative works from, transfer or sell any material contained on the website without the prior consent of the copyright owner. Violation of this provision may result in severe civil and criminal penalties.
Trademarks
Romil Sewa Sanstha® and other marks used on this website are trademarks or registered trademarks of Romil Sewa Sanstha and its affiliates and are protected by state and federal trademark laws. Other trademarks appear on the website with permission from their respective owners. Your unauthorized use of trademarks appearing on the website may constitute trademark infringement, which could subject you to substantial civil penalties.
Termination of Privileges
Romil Sewa Sanstha reserves the right to suspend or terminate your privilege of using all or any portion of this website, including all of your privileges or accounts that you may have established in connection with the website, at any time and without notice to you if, in Romil Sewa Sanstha’s sole judgment, you breach any of these General Terms and Conditions, the Restricted Sites Terms and Conditions, the Romil Sewa Sanstha Privacy Policy or for any other lawful reason. Notwithstanding the termination of your various privileges, the following paragraphs shall survive such termination: Accuracy, Completeness and Timeliness of Information on the Website, Use of Materials from the Website, Materials You Submit, Disclaimers, Limitation of Liability, Indemnification, Copyright, Trademarks, Termination Privileges, Jurisdiction and Miscellaneous.
Changes to These General Terms and Conditions
Romil Sewa Sanstha reserves the right to make changes to these General Terms and Conditions at any time by posting revised General Terms and Conditions on the website. It is your responsibility to check periodically for any changes we may make to these General Terms and Conditions. The most current version of the General Terms and Conditions can be reviewed by clicking on the “Terms and Conditions” hypertext link located at the bottom of our Web pages. By continuing to use the website, you are agreeing to all changes made by Romil Sewa Sanstha.
Jurisdiction
This website is controlled and operated by Romil Sewa Sanstha from its Central office in Delhi, India. The laws of Delhi State govern these General Terms and Conditions and your use of the website. We recognize that it is possible for you to obtain access to this website from any jurisdiction in the world, but we have no practical ability to prevent such access. This website has been designed to comply with the laws of Delhi State, Delhi and India. Those who choose to access the website from other locations do so on their own initiative and are responsible for compliance with local laws if and to the extent local laws are applicable. If any material on this website, or your use of the website, is contrary to the laws of the place where you are when you access it, then the website is not intended for you and we ask you not to use the website. You may not use or export materials on this website in violation of Indian laws and regulations. This website is not intended to subject Romil Sewa Sanstha to the laws or jurisdiction of any state, or territory other than the Delhi & Delhi.
If a dispute arises under these General Terms and conditions between you and Romil Sewa Sanstha, such dispute shall be resolved in (i) Delhi, India; and (ii) at the filing party’s election, in either a small claims court or by final and binding arbitration administered by the National Arbitration Forum/Tribunal under their rules for consumer arbitrations.  All disputes in arbitration will be handled solely between the named parties and not on any representative or class basis.  ACCORDINGLY, YOU ACKNOWLEDGE THAT YOU MAY NOT HAVE ACCESS TO A COURT (OTHER THAN A SMALL CLAIMS COURT) OR JURY. Notwithstanding any other provision of these General Terms and Conditions, Romil Sewa Sanstha may resort to court action for injunctive relief at any time if, in its good faith belief, the dispute resolution procedures described above would permit or cause irreparable injury to  Romil Sewa Sanstha or any third party claiming against a Romil Sewa Sanstha, due to delay arising out of such dispute resolution procedures.
Miscellaneous
If any provision of this agreement is unlawful, void or unenforceable, the remaining provisions of the agreement will remain in place. These General Terms and Conditions constitute the entire agreement and understanding between you and Romila Sewa Sanstha with respect to use of the website, superseding all prior or contemporaneous communications; except that use of any Restricted Sites are governed by the Restricted Sites Terms and Conditions. A printed version of these General Terms and Conditions shall be admissible in judicial or administrative proceedings based on or relating to use of the website to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form.
How to Contact Us
If you have any questions or comments about these General Terms and Conditions or this website, please Contact Us or write to us at:
Romil Sewa Sanstha
C356 Defence Colony, New Delhi 110024
RESTRICTED SITES TERMS AND CONDITIONS
By clicking the “I Agree” button that follows these terms and conditions (“Restricted Sites Terms and Conditions”) or otherwise accessing or using the portions of the Romil Sewa Sanstha website designated for registered users (the “Restricted Sites”), you (“User”) agree as follows:
REGISTRATION; TRANSACTIONS; TERM OF REGISTRATION
Transactions
Method of Payment. In order to complete a Transaction, user may need to provide a method of payment (“Payment Account”) as specified during the registration process. User may execute a single Transaction at a time or execute multiple Transactions on a recurring basis (e.g., monthly, quarterly, annually, etc.), depending upon the options selected during the Transaction process. You authorize Romil Sewa Sanstha to charge your Payment Account at the frequency and in the amounts designated by you during the Transaction process. All fees will be billed via the method of payment you designate during the Transaction process. Once submitted, amounts paid are generally non-refundable. However, in the event your donation was not intended for ChildFund, you may request a refund. Romil Sewa Sanstha may periodically need to increase the donation amount and in such cases, ChildFund will announce the increase before any additional deductions are made. You will always have the option to decline an increase.
Donations. User acknowledges and agrees that Romil Sewa Sanstha did not provide any goods or services to User personally in consideration for any donations made by User as part of a Transaction. Romil Sewa Sanstha will apply User’s donations in accordance with its internal policies and procedures.
Digital Communications
Intellectual Property License.  User owns all of the content and information posted by User on website.  For content and information that is covered by intellectual property rights (“IP Content”), User specifically grants Romil Sewa Sanstha a perpetual, non-exclusive, irrevocable, transferable, sub-licensable, royalty-free, worldwide license to use any IP Content that is posted, uploaded or otherwise stored through User’s use of the features on website.
Notices
All notices from Romil Sewa Sanstha intended for receipt by User shall be deemed delivered and effective when sent to the email address provided by User during the registration process or when posted to and made available to User on the Romil Sewa Sanstha website (www.romilsewasanstha.org)  (in either case, “Notice”). If User changes the email address he or she provided in connection with his or her registration to access and use the Restricted Sites, User must update his or her email address in accordance with the procedures set forth on the Romil Sewa Sanstha website (www.romilsewasanstha.org).
MODIFICATIONS TO THE RESTRICTED SITES / TERMS AND CONDITIONS
Modifications to the Restricted Sites / Terms and Conditions
User acknowledges and agrees that Romil Sewa Sanstha may, in its sole discretion, modify the Restricted Sites and these Restricted Sites Terms and Conditions (including any instructions, policies or guidelines referenced herein) at any time and in any manner. All such modifications shall be binding upon User when made. User may not amend or modify the Restricted Sites or these Restricted Sites Terms and Conditions under any circumstances.
REPRESENTATIONS, COVENANTS AND WARRANTIES
Representations, Covenants and Warranties of User
User represents, covenants and warrants to Romil Sewa Sanstha that (1) these Restricted Sites Terms and Conditions have been executed and delivered by User and constitute a valid and binding agreement of User, enforceable against User in accordance with their terms; (2) User will not access or use the Restricted Sites except as expressly permitted by these Restricted Sites Terms and Conditions and any additional instructions, guidelines or policies issued by Romil Sewa Sanstha, including those posted on the Romil Sewa Sanstha website (www.romilsewasanstha.org); (3) User will access and use the Restricted Sites in full compliance with applicable Law (as defined in the section title “COMPLIANCE” below); (4) User is at least eighteen (18) years old, or, if younger than eighteen (18) years old, User is of an age sufficient to execute a legally enforceable agreement on his or her own behalf in the applicable jurisdiction; (5) all of the information, data and other materials provided by User in support of User’s application for registration are accurate and truthful in all respects; and (6) User is the rightful owner of the any account opened it his or her name, included but not limited to Payment Accounts, and is authorized to commit funds from the relevant accounts to Romil Sewa Sanstha for purposes of conducting Transactions.
Disclaimer
EXCEPT AS OTHERWISE EXPRESSLY PROVIDED IN THESE TERMS AND CONDITIONS, Romil Sewa Sanstha MAKES NO REPRESENTATIONS, COVENANTS OR WARRANTIES AND OFFERS NO OTHER CONDITIONS, EXPRESS OR IMPLIED, REGARDING ANY MATTER, INCLUDING (1) THE MERCHANTABILITY, SUITABILITY, FITNESS FOR A PARTICULAR USE OR PURPOSE, NON-INFRINGEMENT OR RESULTS TO BE DERIVED FROM THE USE OF THE RESTRICTED SITES OR ANY DATA SERVICE, SOFTWARE, HARDWARE, DELIVERABLE, WORK PRODUCT, DIGITAL COMMUNICATIONS OR OTHER MATERIALS RELATED TO THE RESTRICTED SITES, OR THE AVAILABILITY OF ANY OF THE FOREGOING; (2) WHETHER THE INFORMATION AVAILABLE ON THE RESTRICTED SITES IS TRUE, COMPLETE OR ACCURATE; OR (3) THAT TRANSACTION FUNDS WILL BE USED FOR ANY PARTICULAR PURPOSE AND SHALL NOT BE RESPONSIBLE FOR ANY MISUSE OR NON USE OF SUCH FUNDS BY THIRD PARTIES AFTER DONATIONS ARE MADE. FURTHER, Romil Sewa Sanstha DOES NOT REPRESENT, COVENANT OR WARRANT THAT ACCESS TO OR SERVICES PROVIDED BY THE RESTRICTED SITES WILL BE UNINTERRUPTED, ERROR-FREE OR SECURE. USER ACKNOWLEDGES AND AGREES THAT THERE ARE RISKS INHERENT TO TRANSMITTING INFORMATION OVER AND STORING INFORMATION, INCLUDING DIGITAL COMMUNICATIONS, ON THE INTERNET AND OTHER COMPUTER NETWORKS AND THAT Romil Sewa Sanstha IS NOT RESPONSIBLE FOR ANY LOSSES OF USER’S DATA, DIGIAL COMMUNICATIONS, CONFIDENTIALITY OR PRIVACY IN CONNECTION THEREWITH.
COMPLIANCE
Generally
User shall use the Restricted Sites in strict compliance with (1) these Restricted Sites Terms and Conditions; (2) any additional instructions, guidelines or policies issued by Romil Sewa Sanstha, including those posted on the Restricted Sites or on the Romil Sewa Sanstha website (www.romilsewasanstha.org); and (3) all applicable laws, rules and regulations (collectively, “Laws”).
CONTRACTORS
Use of Contractors
Romil Sewa Sanstha may engage any third party (including Romil Sewa Sanstha’s affiliates) to perform, or support the performance of, all or any portion of the Restricted Sites.
INTELLECTUAL PROPERTY RIGHTS; RESTRICTIONS ON USE
Ownership of the Restricted Sites and Related Data
As between Romil Sewa Sanstha and User (collectively, “Parties”), Romil Sewa Sanstha owns and will retain ownership of all rights, title and interest in and to the Restricted Sites, including (1) all content on the Restricted Sites developed by Romil Sewa Sanstha or its third-party licensors, including any derivative works of the Restricted Sites and any such content; (2) any data presented on or by the Restricted Sites or otherwise uploaded, posted, or stored by Romil Sewa Sanstha and its third-party providers, except for personal information that User submits to Romil Sewa Sanstha through the Restricted Sites and except as noted in the section titled “DIGITAL CORRESPONDENCE”; and (3) any intellectual property or other proprietary rights comprising any of the foregoing (collectively, “Romil Sewa Sanstha IP”). Neither these Restricted Sites Terms and Conditions nor any disclosure made hereunder grant any license to User under any Romil Sewa Sanstha IP.
Use of the Restricted Sites
User may use the Restricted Sites, including any data presented on or by the Restricted Sites for User or otherwise hosted or stored by Romil Sewa Sanstha for User, only on its own behalf and for lawful and appropriate purposes. User shall not use the Restricted Sites or any of the data presented on or by the Restricted Sites or otherwise hosted or stored by Romil Sewa Sanstha for any commercial or other purpose other than as expressly permitted herein. User will notify Romil Sewa Sanstha immediately upon any suspected unauthorized use of the Restricted Sites, whether by User or a third party, or any suspected loss of or suspected unauthorized access to passwords or other login information used by user to access the Restricted Sites (“Login Credentials”). User shall be solely responsible for maintaining the confidence and security of any Login Credentials, and Romil Sewa Sanstha shall bear no liability or other responsibility associated therewith.
PRIVACY NOTICE
Privacy Notice/ Policy
User explicitly consents to the collection, hosting, use, disclosure and other processing or handling of information as described in the Romil Sewa Sanstha Privacy Notice/ Policy located at http://www.romilsewasanstha.org/ as such notice may be amended by Romil Sewa Sanstha in its sole discretion from time to time.
SUSPENSION; TERMINATION
Suspension
Romil Sewa Sanstha may suspend or limit User’s access to the Restricted Sites if Romil Sewa Sanstha, in its sole discretion, suspects that User is in violation of, or reasonably likely to be in violation of, these Restricted Sites Terms and Conditions or any additional instructions, guidelines or policies issued by Romil Sewa Sanstha, including those posted on the Romil Sewa Sanstha website (www.romilsewasanstha.org).
Termination by ChildFund
Romil Sewa Sanstha may terminate User’s registration, in whole or in part, as follows:
For Cause. Immediately (1) in order to comply with applicable Law or instructions from any governmental agency or authority; (2) if Romil Sewa Sanstha, in its sole discretion, suspects that User is using the Restricted Sites in a manner not permitted by these Restricted Site Terms and Conditions; or (3) upon any breach of these Restricted Site Terms and Conditions, the Romil Sewa Sanstha Website General Terms and Conditions or the Romil Sewa Sanstha Privacy Policy by User.
For Convenience. For convenience, upon Notice by Romil Sewa Sanstha to User, which may occur after an unsuccessful login attempt by User.
Effect of Termination/Survival of Selected Provisions
Effect of Termination. Upon the expiration or earlier termination of User’s registration, for any reason (i) user will no longer be authorized to access the Restricted Sites or otherwise use any of the features or services offered by the Restricted Sites; (ii) Romil Sewa Sanstha may delete any data associated with User’s accounts, including but not limited to, any content in User’s Account; and (iii) all rights and obligations of the Parties under these Restricted Sites Terms and Conditions shall expire, except those rights and obligations under those sections specifically designated in  the sub-section titled “SURVIVAL” immediately below.
Survival. Notwithstanding the expiration or earlier termination of User’s registration to the Restricted Sites, the following sections of the Restricted Sites Terms and Conditions shall survive any such expiration or termination: “DISCLAIMER”; “OWNERSHIP OF THE WEBSITE AND RELATED DATA”; “EFFECT OF TERMINATION/SURVIVAL OF SELECTED PROVISIONS”; “LIABILITY”; “INDEMNITIES”; “DISPUTE RESOLUTION”; AND, “GENERAL”.
LIABILITY
Limitation of Liability
TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE Romil Sewa Sanstha GROUP (AS DEFINED IN SECTION TITLED “INDEMNITIES”) SHALL NOT BE LIABLE TO USER FOR ANY DIRECT, INDIRECT, SPECIAL, INCIDENTAL, PUNITIVE OR CONSEQUENTIAL DAMAGES ARISING OUT OF OR RESULTING FROM USER’S USE OF THE RESTRICTED SITES, OR BASED UPON ANY BREACH OF ANY EXPRESS OR IMPLIED WARRANTY, BREACH OF CONTRACT (INCLUDING THESE RESTRICTED SITES TERMS AND CONDITIONS AND ANY ADDITIONAL INSTRUCTIONS, GUIDELINES OR POLICIES ISSUED BY Romil Sewa Sanstha, INCLUDING THOSE POSTED ON THE Romil Sewa Sanstha WEBSITE (www.romilsewasanstha.org), NEGLIGENCE, TORT OR ANY OTHER LEGAL THEORY (COLLECTIVELY, THE “EXCLUDED DAMAGES”). THE EXCLUDED DAMAGES ALSO INCLUDE, WITHOUT LIMITATION, LOSS OF SAVINGS AND REVENUE; LOSS OF PROFIT; LOSS OF USE; LOSS OF DATA AND THE CLAIMS OF THIRD PARTIES. IF Romil Sewa Sanstha GROUP CANNOT LAWFULLY DISCLAIM LIABILITY FOR ANY OF THE FOREGOING DAMAGES, THE Romil Sewa Sanstha GROUP’S MAXIMUM LIABILITY TO USER IS LIMITED TO THE AMOUNT OF THE DONATION SUBMITTED BY USER THAT GAVE RISE TO THE UNDERLYING CLAIM, OR, IF NO DONATION WAS PROVIDED, INR 100.00. THESE LIMITATIONS APPLY EVEN IF ANY OTHER REMEDY AVAILABLE TO USER FAILS OF ITS ESSENTIAL PURPOSE. SOME STATES DO NOT ALLOW THE EXCLUSION OR LIMITATION OF INCIDENTAL OR CONSEQUENTIAL DAMAGES, SO THE ABOVE LIMITATION MAY NOT APPLY TO USER.
Remedies
At its option, any member of the Romil Sewa Sanstha Group may seek all remedies available to it under law and in equity, including injunctive relief in the form of specific performance to enforce these Restricted Sites Terms and Conditions, including any additional instructions, guidelines or policies issued by Romil Sewa Sanstha, including those posted on the Romil Sewa Sanstha website (www.romilsewasanstha.org), and/or actions for damages.
Claims
No action arising out of, in connection with, or relating to these Restricted Sites Terms and Conditions or the subject of these Restricted Sites Terms and Conditions shall be brought by User more than one (1) year after the accrual of the cause of action.  This period shall not be extended for any reason, except by the written consent of both parties.  All statutes or provision of law which would toll or otherwise affect the running of the period of limitations are hereby waived, and no such statute or provision of law shall operate to extend the period limited in this paragraph.
INDEMNITIES
Indemnity by User
User will indemnify and hold harmless Romil Sewa Sanstha, its affiliates and their respective current, future or former officers, directors, partners, employees, agents, contractors, and their successors or assigns (collectively, the “Romil Sewa Sanstha Group”) on demand, from and against any and all fines, penalties, liabilities, losses and other damages of any kind whatsoever (including attorneys’ and experts’ fees) incurred by any of the members of the Romil Sewa Sanstha Group, and, if directed by Romil Sewa Sanstha, shall defend the Romil Sewa Sanstha Group against (1) all claims that any information, data or other materials provided by User in connection with the  Restricted Sites (including, but not limited to, User’s application for registration to access and use the Restricted Sites) or these Restricted Sites  Terms and Conditions, or use thereof by any member of the Romil Sewa Sanstha Group, infringes, misappropriates or otherwise violates any patent, trademark, copyright, trade secret or other intellectual property or proprietary right of a third party, or that violates any Law; (2) all claims arising from fraud, intentional misconduct, criminal acts or gross negligence by User; and (3) all claims otherwise arising due to a failure by User to comply with any term or condition of these Restricted Sites Terms and Conditions, including any additional instructions, guidelines or policies issued by Romil Sewa Sanstha, including those posted on the Romil Sewa Sanstha website (www.romilsewasanstha.org).
DISPUTE RESOLUTION
Disputes
If a dispute arises under these Restricted Sites Terms and Conditions between User and any member of the Romil Sewa Sanstha Group, such dispute shall be resolved (i) in Delhi, Delhi State, India and (ii) at the filing party’s election, in either a small claims court or by final and binding arbitration administered by the National Arbitration Forum or the Indian Arbitration Association, under their rules for consumer arbitrations. All disputes in arbitration will be handled solely between the named parties, and not on any representative or class basis. ACCORDINGLY, USER ACKNOWLEDGES THAT IT MAY NOT HAVE ACCESS TO A COURT (OTHER THAN A SMALL CLAIMS COURT) OR JURY. Notwithstanding any other provision of these Restricted Sites Terms and Conditions, any member of the Romil Sewa Sanstha Group may resort to court action for injunctive relief at any time if, in its good faith belief, the dispute resolution procedures described in this Section would permit or cause irreparable injury to such member of the Romil Sewa Sanstha Group or any third party claiming against a member of the Romil Sewa Sanstha Group, due to delay arising out of such dispute resolution.
Governing Law
This Romil Sewa Sanstha website and the Restricted Sites are controlled and operated by Romil Sewa Sanstha from its principal office in Delhi State, India. The laws of Delhi State govern these Restricted Sites Terms and Conditions and your use of the Restricted Sites. We recognize that it is possible for you to obtain access to the Restricted Sites from any jurisdiction in the world, but Romil Sewa Sanstha has no practical ability to prevent such access. The Restricted Sites has been designed to comply with the laws of Delhi State, Delhi and India. User who choose to access the Restricted Sites from other locations do so on their own initiative and are responsible for compliance with local laws, if and to the extent local laws are applicable. If any material on the Restricted Sites, or your use of the Restricted Sites, is contrary to the laws of the place where you are when you access it, then the Restricted Sites are not intended for you and we ask you not to use the Restricted Sites. You may not use or export materials on this website in violation of Indian laws and regulations. The Restricted Sites are not intended to subject Romil Sewa Sanstha to the laws or jurisdiction of any state, or territory other than the Delhi & Delhi.
GENERAL
Entire Agreement, Amendments and Modifications
These Restricted Terms and Conditions, as supplemented by the Romil Sewa Sanstha website General Terms and Conditions, available at www.romilsewasanstha.org and the Romil Sewa Sanstha’s Privacy Policy, available at www.romilsewasanstha.org and any additional instructions, guidelines or policies issued by Romil Sewa Sanstha, including those posted on the Romil Sewa Sanstha’s website (www.romilsewasanstha.org), constitute the entire agreement of the Parties with regard to the Restricted Sites and all matters addressed herein, and all prior agreements, letters, proposals, discussions and other documents regarding the Restricted Sites and the matters herein are superseded and merged into these Restricted Sites Terms and Conditions.
Force Majeure
Romil Sewa Sanstha will be excused from performance under these Restricted Sites Terms and Conditions for any period that it is prevented from or delayed in performing any obligations pursuant to these Restricted Sites Terms and Conditions, in whole or in part, as a result of a Force Majeure Event. For purposes of this Section , “Force Majeure Event” means an event or series of events caused by or resulting from any of the following: (1) weather conditions or other elements of nature or acts of God; (2) acts of war, terrorism, insurrection, riot, civil disorder or rebellion; (3) quarantines or embargoes; (4) labour strikes; (4) telecommunications, network, computer, server or Internet downtime; (5) unauthorized access to Romil Sewa Sanstha’s information technology systems by third parties; or (6) other causes beyond the reasonable control of Romil Sewa Sanstha.
Severability
If any provision of these Restricted Sites Terms and Conditions shall be held to be invalid, illegal or unenforceable, the validity, legality and enforceability of the remaining provisions shall not in any way be affected or impaired thereby, and such provision shall be deemed to be restated to reflect the Parties’ original intentions as nearly as possible in accordance with applicable Law(s).
Assignment
User may not assign these Restricted Sites Terms and Conditions (or any rights, benefits or obligations hereunder) by operation of law or otherwise without the prior written consent of Romil Sewa Sanstha, which may be withheld at Romil Sewa Sanstha’s sole discretion. Any attempted assignment by User that does not comply with the terms of this Section shall be null and void. Romil Sewa Sanstha may assign these Restricted Sites Terms and Conditions, in whole or in part, to any third party in its sole discretion.
        </p>
    </div>
</div>
@endsection